CREATE TABLE "CWSINT"."ALLGTN_T" (
		"IDENTIFIER" CHAR(10) NOT NULL, 
		"ABUSE_ENDT" DATE WITH DEFAULT NULL, 
		"ABUSE_FREQ" SMALLINT NOT NULL WITH DEFAULT, 
		"ABUSE_PDCD" CHAR(1) NOT NULL WITH DEFAULT, 
		"LOC_DSC" CHAR(75) NOT NULL WITH DEFAULT, 
		"ABUSE_STDT" DATE WITH DEFAULT NULL, 
		"ALG_DSPC" SMALLINT NOT NULL WITH DEFAULT, 
		"ALG_TPC" SMALLINT NOT NULL, 
		"DISPSN_DSC" CHAR(254) NOT NULL WITH DEFAULT, 
		"DISPSN_DT" DATE WITH DEFAULT NULL, 
		"IJHM_DET_B" CHAR(1) NOT NULL, 
		"NON_PRT_CD" CHAR(1) NOT NULL, 
		"STFADD_IND" CHAR(1) NOT NULL, 
		"LST_UPD_ID" CHAR(3) NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKCLIENT_T" CHAR(10) NOT NULL, 
		"FKCLIENT_0" CHAR(10) WITH DEFAULT NULL, 
		"FKREFERL_T" CHAR(10) NOT NULL, 
		"CNTY_SPFCD" CHAR(2) NOT NULL, 
		"ZIPPY_IND" CHAR(1) NOT NULL WITH DEFAULT 'N', 
		"PLC_FCLC" SMALLINT WITH DEFAULT NULL
	)CCSID ASCII;

CREATE TABLE "CWSINT"."ALPRHIST" (
		"IDENTIFIER" CHAR(10) NOT NULL, 
		"PR_UPD_DT" DATE NOT NULL, 
		"LST_UPD_ID" CHAR(3) NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKCLIENT_T" CHAR(10) WITH DEFAULT NULL, 
		"FKALLGTN_T" CHAR(10) NOT NULL, 
		"CNTY_SPFCD" CHAR(2) NOT NULL WITH DEFAULT '99'
	)CCSID ASCII;

CREATE TABLE "CWSINT"."CRSS_RPT" (
		"THIRD_ID" CHAR(10) NOT NULL, 
		"XRPT_MTC" SMALLINT NOT NULL, 
		"INFORM_DT" DATE NOT NULL, 
		"OUT_ST_IND" CHAR(1) NOT NULL, 
		"GV_XRPT_B" CHAR(1) NOT NULL, 
		"INFORM_TM" TIME WITH DEFAULT NULL, 
		"RCPT_BDGNO" CHAR(6) NOT NULL WITH DEFAULT, 
		"RCPT_EXTNO" INTEGER NOT NULL WITH DEFAULT, 
		"RCPT_TELNO" DECIMAL(10 , 0) NOT NULL WITH DEFAULT, 
		"POS_TILDSC" CHAR(30) NOT NULL WITH DEFAULT, 
		"REFERNC_NO" CHAR(10) NOT NULL WITH DEFAULT, 
		"LST_UPD_ID" CHAR(3) NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKREFERL_T" CHAR(10) NOT NULL, 
		"FKLAW_ENFT" CHAR(10) WITH DEFAULT NULL, 
		"FKSTFPERST" CHAR(3) NOT NULL, 
		"XRPT_DSC" CHAR(120) NOT NULL WITH DEFAULT, 
		"RECIPNT_NM" CHAR(40) NOT NULL WITH DEFAULT, 
		"OSLWNFADDR" CHAR(254) NOT NULL WITH DEFAULT, 
		"CNTY_SPFCD" CHAR(2) NOT NULL, 
		"LAW_IND" CHAR(1) NOT NULL WITH DEFAULT 'N', 
		"OS_LAW_IND" CHAR(1) NOT NULL WITH DEFAULT 'N', 
		"SXRPT_IND" CHAR(1) NOT NULL WITH DEFAULT 'N'
	)CCSID ASCII;

CREATE TABLE "CWSINT"."GRV_REQT" (
		"FKREFERL_T" CHAR(10) NOT NULL, 
		"FKCLIENT_T" CHAR(10) NOT NULL, 
		"THIRD_ID" CHAR(10) NOT NULL, 
		"REQUEST_DT" DATE NOT NULL, 
		"RESOLTN_DT" DATE WITH DEFAULT NULL, 
		"OUTCOME_CD" CHAR(1) WITH DEFAULT NULL, 
		"CNTY_SPFCD" CHAR(2) NOT NULL, 
		"LST_UPD_ID" CHAR(3) NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL
	)CCSID ASCII;

CREATE TABLE "CWSINT"."GV_XRPT" (
		"THIRD_ID" CHAR(10) NOT NULL, 
		"LST_UPD_ID" CHAR(3) NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKCRSS_RPT" CHAR(10) NOT NULL, 
		"FKCRSS_RP0" CHAR(10) NOT NULL, 
		"FKGV_ORG_T" CHAR(10) WITH DEFAULT NULL, 
		"CNTY_SPFCD" CHAR(2) NOT NULL, 
		"ORG_TY_IND" CHAR(1) NOT NULL
	)CCSID ASCII;

CREATE TABLE "CWSINT"."IJBD_DET" (
		"THIRD_ID" CHAR(10) NOT NULL, 
		"ABS_BPTC" SMALLINT NOT NULL, 
		"LST_UPD_ID" CHAR(3) NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKIJHM_DET" CHAR(10) NOT NULL, 
		"FKIJHM_DE0" CHAR(10) NOT NULL, 
		"CNTY_SPFCD" CHAR(2) NOT NULL
	)CCSID ASCII;

CREATE TABLE "CWSINT"."IJHM_DET" (
		"THIRD_ID" CHAR(10) NOT NULL, 
		"INJR_HMC" SMALLINT NOT NULL, 
		"IJBD_DET_B" CHAR(1) NOT NULL, 
		"LST_UPD_ID" CHAR(3) NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKALLGTN_T" CHAR(10) NOT NULL, 
		"CNTY_SPFCD" CHAR(2) NOT NULL
	)CCSID ASCII;

CREATE TABLE "CWSINT"."I_AND_RT" (
		"THIRD_ID" CHAR(10) NOT NULL, 
		"RFRD_RSC" SMALLINT NOT NULL WITH DEFAULT, 
		"LST_UPD_ID" CHAR(3) NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKSTFPERST" CHAR(3) NOT NULL, 
		"CNTY_SPFCD" CHAR(2) NOT NULL
	)CCSID ASCII;

CREATE TABLE "CWSINT"."REFERL_T" (
		"IDENTIFIER" CHAR(10) NOT NULL, 
		"ADD_INF_CD" CHAR(1) NOT NULL WITH DEFAULT, 
		"ANRPTR_IND" CHAR(1) NOT NULL, 
		"PETAPL_IND" CHAR(1) NOT NULL, 
		"APRVL_NO" CHAR(10) WITH DEFAULT NULL, 
		"APV_STC" SMALLINT NOT NULL, 
		"CR_PERP_CD" CHAR(1) NOT NULL WITH DEFAULT, 
		"REFCLSR_DT" DATE WITH DEFAULT NULL, 
		"CMM_MTHC" SMALLINT NOT NULL, 
		"CHILOC_TXT" CHAR(10) WITH DEFAULT NULL, 
		"ALGDSC_DOC" CHAR(10) WITH DEFAULT NULL, 
		"ER_REF_DOC" CHAR(10) WITH DEFAULT NULL, 
		"INVSTG_DOC" CHAR(10) WITH DEFAULT NULL, 
		"XRPT_LWIND" CHAR(1) NOT NULL, 
		"FMY_AW_IND" CHAR(1) NOT NULL, 
		"GVR_ENTC" SMALLINT NOT NULL WITH DEFAULT, 
		"LGL_DEF_CD" CHAR(1) NOT NULL WITH DEFAULT, 
		"LGLRGT_IND" CHAR(1) NOT NULL, 
		"LMT_ACSSCD" CHAR(1) NOT NULL, 
		"XRPT_RCVDT" DATE WITH DEFAULT NULL, 
		"REFERRL_NM" CHAR(35) NOT NULL WITH DEFAULT, 
		"ADQT_CS_CD" CHAR(1) NOT NULL WITH DEFAULT, 
		"REF_RCV_DT" DATE NOT NULL, 
		"REF_RCV_TM" TIME NOT NULL, 
		"RFR_RSPC" SMALLINT NOT NULL WITH DEFAULT, 
		"RFRD_RSC" SMALLINT NOT NULL WITH DEFAULT, 
		"RSP_DTR_DT" DATE WITH DEFAULT NULL, 
		"RSP_DTR_TM" TIME WITH DEFAULT NULL, 
		"RSP_RTNTXT" CHAR(10) WITH DEFAULT NULL, 
		"SCN_NT_TXT" CHAR(10) WITH DEFAULT NULL, 
		"SP_INCL_CD" CHAR(1) NOT NULL WITH DEFAULT, 
		"SFC_INF_CD" CHAR(1) NOT NULL WITH DEFAULT, 
		"UNFD_SR_CD" CHAR(1) NOT NULL WITH DEFAULT, 
		"LST_UPD_ID" CHAR(3) NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKREFERL_T" CHAR(10) WITH DEFAULT NULL, 
		"FKADDRS_T" CHAR(10) WITH DEFAULT NULL, 
		"FKSTFPERS0" CHAR(3) WITH DEFAULT NULL, 
		"FKSTFPERST" CHAR(3) NOT NULL, 
		"CNTY_SPFCD" CHAR(2) NOT NULL, 
		"SPRJRF_IND" CHAR(1) NOT NULL WITH DEFAULT 'N', 
		"ZIPPY_IND" CHAR(1) NOT NULL WITH DEFAULT 'N', 
		"HOMLES_IND" CHAR(1) NOT NULL WITH DEFAULT 'N', 
		"FAMREF_IND" CHAR(1) NOT NULL WITH DEFAULT 'N', 
		"FIRST_EODT" DATE WITH DEFAULT NULL, 
		"RSP_AGY_CD" CHAR(1) NOT NULL WITH DEFAULT 'C', 
		"L_GVR_ENTC" SMALLINT WITH DEFAULT NULL, 
		"LMT_ACS_DT" DATE WITH DEFAULT NULL, 
		"LMT_ACSDSC" CHAR(254) WITH DEFAULT NULL, 
		"ORIGCLS_DT" DATE WITH DEFAULT NULL
	)
	CCSID ASCII;
	
CREATE TABLE "CWSINT"."REFRHIST" (
		"FKREFERL_T" CHAR(10) NOT NULL, 
		"THIRD_ID" CHAR(10) NOT NULL, 
		"REOPEN_DT" DATE NOT NULL, 
		"REFCLSR_DT" DATE WITH DEFAULT NULL, 
		"REFROPNC" SMALLINT NOT NULL, 
		"REOPEN_DSC" CHAR(254) WITH DEFAULT NULL, 
		"FKSTFPERST" CHAR(3) NOT NULL, 
		"LST_UPD_ID" CHAR(3) NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"CNTY_SPFCD" CHAR(2) NOT NULL
	)CCSID ASCII;

CREATE TABLE "CWSINT"."REFR_CLT" (
		"APRVL_NO" CHAR(10) WITH DEFAULT NULL, 
		"APV_STC" SMALLINT NOT NULL, 
		"DSP_RSNC" SMALLINT NOT NULL WITH DEFAULT, 
		"DISPSTN_CD" CHAR(1) NOT NULL WITH DEFAULT, 
		"RCL_DISPDT" DATE WITH DEFAULT NULL, 
		"SLFRPT_IND" CHAR(1) NOT NULL, 
		"STFADD_IND" CHAR(1) NOT NULL, 
		"LST_UPD_ID" CHAR(3) NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKCLIENT_T" CHAR(10) NOT NULL, 
		"FKREFERL_T" CHAR(10) NOT NULL, 
		"DSP_CLSDSC" CHAR(254) NOT NULL WITH DEFAULT, 
		"RFCL_AGENO" SMALLINT NOT NULL WITH DEFAULT, 
		"AGE_PRD_CD" CHAR(1) NOT NULL WITH DEFAULT, 
		"CNTY_SPFCD" CHAR(2) NOT NULL, 
		"MHLTH_IND" CHAR(1) WITH DEFAULT NULL, 
		"ALCHL_IND" CHAR(1) WITH DEFAULT NULL, 
		"DRUG_IND" CHAR(1) WITH DEFAULT NULL
	)CCSID ASCII;

CREATE TABLE "CWSINT"."REPTR_T" (
		"RPTR_BDGNO" CHAR(6) NOT NULL WITH DEFAULT, 
		"RPTR_CTYNM" CHAR(20) NOT NULL WITH DEFAULT, 
		"COL_RELC" SMALLINT NOT NULL WITH DEFAULT, 
		"CMM_MTHC" SMALLINT NOT NULL WITH DEFAULT, 
		"CNFWVR_IND" CHAR(1) NOT NULL, 
		"FDBACK_DOC" CHAR(10) WITH DEFAULT NULL, 
		"RPTR_EMPNM" CHAR(35) NOT NULL WITH DEFAULT, 
		"FEEDBCK_DT" DATE WITH DEFAULT NULL, 
		"FB_RQR_IND" CHAR(1) NOT NULL WITH DEFAULT, 
		"RPTR_FSTNM" CHAR(20) NOT NULL WITH DEFAULT, 
		"RPTR_LSTNM" CHAR(25) NOT NULL WITH DEFAULT, 
		"MNRPTR_IND" CHAR(1) NOT NULL, 
		"MSG_EXT_NO" INTEGER NOT NULL WITH DEFAULT, 
		"MSG_TEL_NO" DECIMAL(10 , 0) NOT NULL WITH DEFAULT, 
		"MID_INI_NM" CHAR(1) NOT NULL WITH DEFAULT, 
		"NMPRFX_DSC" CHAR(6) NOT NULL WITH DEFAULT, 
		"PRM_TEL_NO" DECIMAL(10 , 0) NOT NULL WITH DEFAULT, 
		"PRM_EXT_NO" INTEGER NOT NULL WITH DEFAULT, 
		"STATE_C" SMALLINT NOT NULL WITH DEFAULT, 
		"RPTR_ST_NM" CHAR(40) NOT NULL WITH DEFAULT, 
		"RPTR_ST_NO" CHAR(10) NOT NULL WITH DEFAULT, 
		"SUFX_TLDSC" CHAR(4) NOT NULL WITH DEFAULT, 
		"RPTR_ZIPNO" INTEGER NOT NULL WITH DEFAULT, 
		"LST_UPD_ID" CHAR(3) NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKREFERL_T" CHAR(10) NOT NULL, 
		"FKLAW_ENFT" CHAR(10) WITH DEFAULT NULL, 
		"ZIP_SFX_NO" SMALLINT NOT NULL WITH DEFAULT, 
		"CNTY_SPFCD" CHAR(2) NOT NULL
	)CCSID ASCII;

CREATE TABLE "CWSINT"."SFSUR_BT" (
		"SURR_DT" DATE NOT NULL, 
		"SURR_TM" TIME WITH DEFAULT NULL, 
		"SURR_BY_NM" CHAR(40) NOT NULL, 
		"RELTO_CLT" SMALLINT NOT NULL, 
		"COMM_DESC" CHAR(254) WITH DEFAULT NULL, 
		"ID_INFO_CD" CHAR(1) NOT NULL WITH DEFAULT 'U', 
		"MEDQUES_CD" CHAR(1) NOT NULL WITH DEFAULT 'U', 
		"QUESREC_DT" DATE WITH DEFAULT NULL, 
		"CPSNTF_IND" CHAR(1) NOT NULL WITH DEFAULT 'N', 
		"CPSNTF_DT" DATE NOT NULL, 
		"CPSNTF_TM" TIME WITH DEFAULT NULL, 
		"LST_UPD_ID" CHAR(3) NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKCHLD_CLT" CHAR(10) NOT NULL, 
		"FKSPRJ_CST" CHAR(10) WITH DEFAULT NULL, 
		"FKSPRJ_RFT" CHAR(10) WITH DEFAULT NULL
	)CCSID ASCII;

CREATE TABLE "CWSINT"."SPRJ_RFT" (
		"THIRD_ID" CHAR(10) NOT NULL, 
		"CNTY_SPFCD" CHAR(2) NOT NULL WITH DEFAULT '99', 
		"LST_UPD_ID" CHAR(3) NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"PART_ENDT" DATE WITH DEFAULT NULL, 
		"PART_STRDT" DATE NOT NULL, 
		"FKREFERL_T" CHAR(10) NOT NULL, 
		"FKSPC_PRJT" CHAR(10) NOT NULL, 
		"SFSURB_IND" CHAR(1) NOT NULL WITH DEFAULT 'N'
	)CCSID ASCII;
	
CREATE TABLE "CWSINT"."SURB_RCT" (
		"THIRD_ID" CHAR(10) NOT NULL, 
		"ATPRCLM_NM" CHAR(40) WITH DEFAULT NULL, 
		"RELTO_CLNT" SMALLINT NOT NULL, 
		"RCLM_DT" DATE WITH DEFAULT NULL, 
		"RCLM_TM" TIME WITH DEFAULT NULL, 
		"RCLM_DESC" CHAR(254) WITH DEFAULT NULL, 
		"SURCLM_IND" CHAR(1) NOT NULL WITH DEFAULT 'N', 
		"LST_UPD_ID" CHAR(3) NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKSFSUR_BT" CHAR(10) NOT NULL
	)CCSID ASCII;	
	
CREATE TABLE "CWSINT"."ADDRS_T" (
		"IDENTIFIER" CHAR(10)  NOT NULL, 
		"CITY_NM" CHAR(20)  NOT NULL WITH DEFAULT, 
		"EMRG_TELNO" DECIMAL(10 , 0) NOT NULL WITH DEFAULT, 
		"EMRG_EXTNO" INTEGER NOT NULL WITH DEFAULT, 
		"FRG_ADRT_B" CHAR(1)  NOT NULL, 
		"GVR_ENTC" SMALLINT NOT NULL WITH DEFAULT, 
		"MSG_TEL_NO" DECIMAL(10 , 0) NOT NULL WITH DEFAULT, 
		"MSG_EXT_NO" INTEGER NOT NULL WITH DEFAULT, 
		"HEADER_ADR" CHAR(35)  NOT NULL WITH DEFAULT, 
		"PRM_TEL_NO" DECIMAL(10 , 0) NOT NULL WITH DEFAULT, 
		"PRM_EXT_NO" INTEGER NOT NULL WITH DEFAULT, 
		"STATE_C" SMALLINT NOT NULL WITH DEFAULT, 
		"STREET_NM" CHAR(40)  NOT NULL WITH DEFAULT, 
		"STREET_NO" CHAR(10)  NOT NULL WITH DEFAULT, 
		"ZIP_NO" INTEGER NOT NULL WITH DEFAULT, 
		"LST_UPD_ID" CHAR(3)  NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"ADDR_DSC" CHAR(120)  NOT NULL WITH DEFAULT, 
		"ZIP_SFX_NO" SMALLINT NOT NULL WITH DEFAULT, 
		"POSTDIR_CD" CHAR(2)  NOT NULL WITH DEFAULT, 
		"PREDIR_CD" CHAR(2)  NOT NULL WITH DEFAULT, 
		"ST_SFX_C" SMALLINT NOT NULL WITH DEFAULT, 
		"UNT_DSGC" SMALLINT NOT NULL WITH DEFAULT, 
		"UNIT_NO" CHAR(8)  NOT NULL WITH DEFAULT
	)CCSID ASCII;
	
CREATE TABLE "CWSINT"."CLIENT_T" (
		"IDENTIFIER" CHAR(10)  NOT NULL, 
		"ADPTN_STCD" CHAR(1)  NOT NULL, 
		"ALN_REG_NO" CHAR(12)  NOT NULL WITH DEFAULT, 
		"BIRTH_DT" DATE WITH DEFAULT NULL, 
		"BR_FAC_NM" CHAR(35)  NOT NULL WITH DEFAULT, 
		"B_STATE_C" SMALLINT NOT NULL WITH DEFAULT, 
		"B_CNTRY_C" SMALLINT NOT NULL WITH DEFAULT, 
		"CHLD_CLT_B" CHAR(1)  NOT NULL, 
		"COM_FST_NM" CHAR(20)  NOT NULL, 
		"COM_LST_NM" CHAR(25)  NOT NULL, 
		"COM_MID_NM" CHAR(20)  NOT NULL WITH DEFAULT, 
		"CONF_EFIND" CHAR(1)  NOT NULL, 
		"CONF_ACTDT" DATE WITH DEFAULT NULL, 
		"CREATN_DT" DATE NOT NULL, 
		"DEATH_DT" DATE WITH DEFAULT NULL, 
		"DTH_RN_TXT" CHAR(10)  WITH DEFAULT NULL, 
		"DRV_LIC_NO" CHAR(20)  NOT NULL WITH DEFAULT, 
		"D_STATE_C" SMALLINT NOT NULL WITH DEFAULT, 
		"GENDER_CD" CHAR(1)  NOT NULL, 
		"I_CNTRY_C" SMALLINT NOT NULL WITH DEFAULT, 
		"IMGT_STC" SMALLINT NOT NULL WITH DEFAULT, 
		"INCAPC_CD" CHAR(2)  NOT NULL, 
		"LITRATE_CD" CHAR(1)  NOT NULL, 
		"MAR_HIST_B" CHAR(1)  NOT NULL, 
		"MRTL_STC" SMALLINT NOT NULL WITH DEFAULT, 
		"MILT_STACD" CHAR(1)  NOT NULL, 
		"NMPRFX_DSC" CHAR(6)  NOT NULL WITH DEFAULT, 
		"NAME_TPC" SMALLINT NOT NULL, 
		"OUTWRT_IND" CHAR(1)  NOT NULL, 
		"P_ETHNCTYC" SMALLINT NOT NULL WITH DEFAULT, 
		"P_LANG_TPC" SMALLINT NOT NULL WITH DEFAULT, 
		"RLGN_TPC" SMALLINT NOT NULL WITH DEFAULT, 
		"S_LANG_TC" SMALLINT NOT NULL WITH DEFAULT, 
		"SENSTV_IND" CHAR(1)  NOT NULL, 
		"SNTV_HLIND" CHAR(1)  NOT NULL, 
		"SS_NO" CHAR(9)  NOT NULL WITH DEFAULT, 
		"SSN_CHG_CD" CHAR(1)  NOT NULL, 
		"SUFX_TLDSC" CHAR(4)  NOT NULL WITH DEFAULT, 
		"UNEMPLY_CD" CHAR(2)  NOT NULL, 
		"LST_UPD_ID" CHAR(3)  NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"COMMNT_DSC" CHAR(120)  NOT NULL WITH DEFAULT, 
		"EST_DOB_CD" CHAR(1)  NOT NULL, 
		"BP_VER_IND" CHAR(1)  NOT NULL WITH DEFAULT, 
		"HISP_CD" CHAR(1)  NOT NULL WITH DEFAULT, 
		"CURRCA_IND" CHAR(1)  NOT NULL WITH DEFAULT 'N', 
		"CURREG_IND" CHAR(1)  NOT NULL WITH DEFAULT 'N', 
		"COTH_DESC" CHAR(25)  NOT NULL WITH DEFAULT, 
		"PREVCA_IND" CHAR(1)  NOT NULL WITH DEFAULT 'N', 
		"PREREG_IND" CHAR(1)  NOT NULL WITH DEFAULT 'N', 
		"POTH_DESC" CHAR(25)  NOT NULL WITH DEFAULT, 
		"HCARE_IND" CHAR(1)  NOT NULL WITH DEFAULT 'N', 
		"LIMIT_IND" CHAR(1)  NOT NULL WITH DEFAULT 'N', 
		"BIRTH_CITY" CHAR(35)  NOT NULL WITH DEFAULT, 
		"HEALTH_TXT" CHAR(10)  WITH DEFAULT NULL, 
		"MTERM_DT" DATE WITH DEFAULT NULL, 
		"FTERM_DT" DATE WITH DEFAULT NULL, 
		"ZIPPY_IND" CHAR(1)  NOT NULL WITH DEFAULT 'N', 
		"DEATH_PLC" CHAR(35)  WITH DEFAULT NULL, 
		"TR_MBVRT_B" CHAR(1)  NOT NULL WITH DEFAULT 'N', 
		"TRBA_CLT_B" CHAR(1)  NOT NULL WITH DEFAULT 'N', 
		"SOC158_IND" CHAR(1)  NOT NULL WITH DEFAULT 'N', 
		"DTH_DT_IND" CHAR(1)  NOT NULL WITH DEFAULT 'N', 
		"EMAIL_ADDR" CHAR(50)  WITH DEFAULT NULL, 
		"ADJDEL_IND" CHAR(1)  WITH DEFAULT NULL, 
		"ETH_UD_CD" CHAR(1)  WITH DEFAULT NULL, 
		"HISP_UD_CD" CHAR(1)  WITH DEFAULT NULL, 
		"SOCPLC_CD" CHAR(1)  NOT NULL WITH DEFAULT 'N', 
		"CL_INDX_NO" CHAR(12)  WITH DEFAULT NULL
	)CCSID ASCII;

CREATE TABLE "CWSINT"."ASGNM_T" (
		"IDENTIFIER" CHAR(10)  NOT NULL, 
		"END_DT" DATE WITH DEFAULT NULL, 
		"END_TM" TIME WITH DEFAULT NULL, 
		"ESTBLSH_ID" CHAR(10)  NOT NULL, 
		"ESTBLSH_CD" CHAR(1)  NOT NULL, 
		"ASSG_RLC" SMALLINT NOT NULL WITH DEFAULT, 
		"START_DT" DATE NOT NULL, 
		"START_TM" TIME NOT NULL, 
		"ASGNMNT_CD" CHAR(1)  NOT NULL, 
		"WGHTNG_NO" DECIMAL(5 , 3) NOT NULL WITH DEFAULT, 
		"LST_UPD_ID" CHAR(3)  NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKOST_PTYT" CHAR(10)  WITH DEFAULT NULL, 
		"FKCASE_LDT" CHAR(10)  WITH DEFAULT NULL, 
		"RESPL_DSC" CHAR(160)  NOT NULL WITH DEFAULT, 
		"CNTY_SPFCD" CHAR(2)  NOT NULL
	)CCSID ASCII;

CREATE TABLE "CWSINT"."STFPERST" (
		"IDENTIFIER" CHAR(3)  NOT NULL, 
		"END_DT" DATE WITH DEFAULT NULL, 
		"FIRST_NM" CHAR(20)  NOT NULL, 
		"JOB_TL_DSC" CHAR(30)  NOT NULL WITH DEFAULT, 
		"LAST_NM" CHAR(25)  NOT NULL, 
		"MID_INI_NM" CHAR(1)  NOT NULL WITH DEFAULT, 
		"NMPRFX_DSC" CHAR(6)  NOT NULL WITH DEFAULT, 
		"PHONE_NO" DECIMAL(10 , 0) NOT NULL, 
		"TEL_EXT_NO" INTEGER NOT NULL WITH DEFAULT, 
		"START_DT" DATE NOT NULL, 
		"SUFX_TLDSC" CHAR(4)  NOT NULL WITH DEFAULT, 
		"TLCMTR_IND" CHAR(1)  NOT NULL, 
		"LST_UPD_ID" CHAR(3)  NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKCWS_OFFT" CHAR(10)  NOT NULL, 
		"AVLOC_DSC" CHAR(160)  NOT NULL WITH DEFAULT, 
		"SSRS_WKRID" CHAR(4)  NOT NULL WITH DEFAULT, 
		"CNTY_SPFCD" CHAR(2)  NOT NULL, 
		"DTYWKR_IND" CHAR(1)  NOT NULL WITH DEFAULT 'N', 
		"FKCWSADDRT" CHAR(10)  NOT NULL WITH DEFAULT, 
		"EMAIL_ADDR" CHAR(50)  WITH DEFAULT NULL
	)CCSID ASCII;
	
CREATE TABLE "CWSINT"."SPV_APVT" (
		"IDENTIFIER" CHAR(10)  NOT NULL, 
		"ACTION_DT" DATE NOT NULL, 
		"ACTION_TM" TIME NOT NULL, 
		"APRVL_NO" CHAR(10)  NOT NULL, 
		"APV_STC" SMALLINT NOT NULL, 
		"APRVL_C" SMALLINT NOT NULL, 
		"CUR_APVIND" CHAR(1)  NOT NULL, 
		"ESTB_FORID" CHAR(10)  NOT NULL, 
		"ESTB_FORCD" CHAR(1)  NOT NULL, 
		"LST_UPD_ID" CHAR(3)  NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKSTFPERST" CHAR(3)  NOT NULL, 
		"FKSTFPERS0" CHAR(3)  WITH DEFAULT NULL, 
		"CS_REF_NM" CHAR(254)  NOT NULL, 
		"SPV_COMDSC" CHAR(254)  NOT NULL WITH DEFAULT, 
		"CNTY_SPFCD" CHAR(2)  NOT NULL
	)CCSID ASCII;	
	
CREATE TABLE "CWSINT"."FRG_ADRT" (
		"IDENTIFIER" CHAR(10)  NOT NULL, 
		"CNTRY_C" SMALLINT NOT NULL, 
		"FRG_ADRDSC" CHAR(40)  NOT NULL WITH DEFAULT, 
		"PRMY_ADRID" CHAR(10)  NOT NULL, 
		"PRMY_ADRCD" CHAR(1)  NOT NULL, 
		"ZIP_ADR" CHAR(10)  NOT NULL WITH DEFAULT, 
		"LST_UPD_ID" CHAR(3)  NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL
	)CCSID ASCII;

CREATE TABLE "CWSINT"."LAW_ENFT" (
		"IDENTIFIER" CHAR(10)  NOT NULL, 
		"CITY_NM" CHAR(20)  NOT NULL, 
		"CNT_PERSNM" CHAR(35)  NOT NULL WITH DEFAULT, 
		"CNT_TEL_NO" DECIMAL(10 , 0) NOT NULL WITH DEFAULT, 
		"CNT_EXT_NO" INTEGER NOT NULL WITH DEFAULT, 
		"CNTITL_DSC" CHAR(30)  NOT NULL WITH DEFAULT, 
		"FAX_NO" DECIMAL(10 , 0) NOT NULL WITH DEFAULT, 
		"GVR_ENTC" SMALLINT NOT NULL WITH DEFAULT, 
		"LAW_ENF_NM" CHAR(35)  NOT NULL, 
		"STATE_C" SMALLINT NOT NULL, 
		"STATION_NM" CHAR(20)  NOT NULL WITH DEFAULT, 
		"STREET_NM" CHAR(40)  NOT NULL, 
		"STREET_NO" CHAR(10)  NOT NULL WITH DEFAULT, 
		"ZIP_NO" INTEGER NOT NULL, 
		"LST_UPD_ID" CHAR(3)  NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"ZIP_SFX_NO" SMALLINT NOT NULL WITH DEFAULT, 
		"ARCASS_IND" CHAR(1)  NOT NULL WITH DEFAULT 'N', 
		"EMAIL_ADDR" CHAR(50)  WITH DEFAULT NULL
	)CCSID ASCII;
	
CREATE TABLE "CWSINT"."SPC_PRJT" (
		"IDENTIFIER" CHAR(10)  NOT NULL, 
		"PRJCT_DSC" CHAR(254)  NOT NULL WITH DEFAULT, 
		"END_DT" DATE WITH DEFAULT NULL, 
		"GVR_ENTC" SMALLINT NOT NULL, 
		"PROJECT_NM" CHAR(30)  NOT NULL WITH DEFAULT, 
		"START_DT" DATE NOT NULL, 
		"LST_UPD_ID" CHAR(3)  NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"ARCASS_IND" CHAR(1)  NOT NULL WITH DEFAULT 'N'
	)CCSID ASCII;
	
CREATE TABLE "CWSINT"."CASE_T" (
		"IDENTIFIER" CHAR(10)  NOT NULL, 
		"START_DT" DATE NOT NULL, 
		"SRV_CMPC" SMALLINT NOT NULL, 
		"APRVL_NO" CHAR(10)  WITH DEFAULT NULL, 
		"APV_STC" SMALLINT NOT NULL, 
		"CLS_RSNC" SMALLINT NOT NULL WITH DEFAULT, 
		"CSPL_DET_B" CHAR(1)  NOT NULL, 
		"CL_STM_TXT" CHAR(10)  WITH DEFAULT NULL, 
		"CNTRY_C" SMALLINT NOT NULL, 
		"NOTES_DOC" CHAR(10)  WITH DEFAULT NULL, 
		"END_DT" DATE WITH DEFAULT NULL, 
		"GVR_ENTC" SMALLINT NOT NULL WITH DEFAULT, 
		"ICPCSTAT_B" CHAR(1)  NOT NULL, 
		"ICPC_RQT_B" CHAR(1)  NOT NULL, 
		"LMT_ACSSCD" CHAR(1)  NOT NULL, 
		"CASE_NM" CHAR(35)  NOT NULL, 
		"PRJ_END_DT" DATE WITH DEFAULT NULL, 
		"SPRJ_CST_B" CHAR(1)  NOT NULL, 
		"STATE_C" SMALLINT NOT NULL WITH DEFAULT, 
		"TICKLE_T_B" CHAR(1)  NOT NULL, 
		"LST_UPD_ID" CHAR(3)  NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKCHLD_CLT" CHAR(10)  NOT NULL, 
		"SRV_CMPDT" DATE NOT NULL, 
		"FKSTFPERST" CHAR(3)  NOT NULL, 
		"CNTY_SPFCD" CHAR(2)  NOT NULL, 
		"ALERT_TXT" CHAR(10)  WITH DEFAULT NULL, 
		"FKREFERL_T" CHAR(10)  WITH DEFAULT NULL, 
		"RSP_AGY_CD" CHAR(1)  WITH DEFAULT 'C', 
		"NXT_TILPDT" DATE WITH DEFAULT NULL, 
		"EMANCPN_DT" DATE WITH DEFAULT NULL, 
		"L_GVR_ENTC" SMALLINT WITH DEFAULT NULL, 
		"LMT_ACS_DT" DATE WITH DEFAULT NULL, 
		"LMT_ACSDSC" CHAR(254)  WITH DEFAULT NULL
	)CCSID ASCII;
	
CREATE TABLE "CWSINT"."OTH_DOCT" (
		"TITLE_NM" CHAR(40)  NOT NULL, 
		"LST_UPD_ID" CHAR(3)  NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKDRMSDOCT" CHAR(10)  NOT NULL, 
		"FKREFERL_T" CHAR(10)  WITH DEFAULT NULL, 
		"CNTY_SPFCD" CHAR(2)  NOT NULL, 
		"DOC_EXTC" SMALLINT NOT NULL WITH DEFAULT 6372, 
		"DOC_LEN" INTEGER NOT NULL WITH DEFAULT
	)CCSID ASCII;
	
CREATE TABLE "CWSINT"."CNTYOWNT" (
		"ENTITY_ID" CHAR(10)  NOT NULL, 
		"ENTITY_CD" CHAR(2)  NOT NULL, 
		"MULTI_FLG" CHAR(1)  NOT NULL, 
		"CTY_00_FLG" CHAR(1)  NOT NULL, 
		"CTY_01_FLG" CHAR(1)  NOT NULL, 
		"CTY_02_FLG" CHAR(1)  NOT NULL, 
		"CTY_03_FLG" CHAR(1)  NOT NULL, 
		"CTY_04_FLG" CHAR(1)  NOT NULL, 
		"CTY_05_FLG" CHAR(1)  NOT NULL, 
		"CTY_06_FLG" CHAR(1)  NOT NULL, 
		"CTY_07_FLG" CHAR(1)  NOT NULL, 
		"CTY_08_FLG" CHAR(1)  NOT NULL, 
		"CTY_09_FLG" CHAR(1)  NOT NULL, 
		"CTY_10_FLG" CHAR(1)  NOT NULL, 
		"CTY_11_FLG" CHAR(1)  NOT NULL, 
		"CTY_12_FLG" CHAR(1)  NOT NULL, 
		"CTY_13_FLG" CHAR(1)  NOT NULL, 
		"CTY_14_FLG" CHAR(1)  NOT NULL, 
		"CTY_15_FLG" CHAR(1)  NOT NULL, 
		"CTY_16_FLG" CHAR(1)  NOT NULL, 
		"CTY_17_FLG" CHAR(1)  NOT NULL, 
		"CTY_18_FLG" CHAR(1)  NOT NULL, 
		"CTY_19_FLG" CHAR(1)  NOT NULL, 
		"CTY_20_FLG" CHAR(1)  NOT NULL, 
		"CTY_21_FLG" CHAR(1)  NOT NULL, 
		"CTY_22_FLG" CHAR(1)  NOT NULL, 
		"CTY_23_FLG" CHAR(1)  NOT NULL, 
		"CTY_24_FLG" CHAR(1)  NOT NULL, 
		"CTY_25_FLG" CHAR(1)  NOT NULL, 
		"CTY_26_FLG" CHAR(1)  NOT NULL, 
		"CTY_27_FLG" CHAR(1)  NOT NULL, 
		"CTY_28_FLG" CHAR(1)  NOT NULL, 
		"CTY_29_FLG" CHAR(1)  NOT NULL, 
		"CTY_30_FLG" CHAR(1)  NOT NULL, 
		"CTY_31_FLG" CHAR(1)  NOT NULL, 
		"CTY_32_FLG" CHAR(1)  NOT NULL, 
		"CTY_33_FLG" CHAR(1)  NOT NULL, 
		"CTY_34_FLG" CHAR(1)  NOT NULL, 
		"CTY_35_FLG" CHAR(1)  NOT NULL, 
		"CTY_36_FLG" CHAR(1)  NOT NULL, 
		"CTY_37_FLG" CHAR(1)  NOT NULL, 
		"CTY_38_FLG" CHAR(1)  NOT NULL, 
		"CTY_39_FLG" CHAR(1)  NOT NULL, 
		"CTY_40_FLG" CHAR(1)  NOT NULL, 
		"CTY_41_FLG" CHAR(1)  NOT NULL, 
		"CTY_42_FLG" CHAR(1)  NOT NULL, 
		"CTY_43_FLG" CHAR(1)  NOT NULL, 
		"CTY_44_FLG" CHAR(1)  NOT NULL, 
		"CTY_45_FLG" CHAR(1)  NOT NULL, 
		"CTY_46_FLG" CHAR(1)  NOT NULL, 
		"CTY_47_FLG" CHAR(1)  NOT NULL, 
		"CTY_48_FLG" CHAR(1)  NOT NULL, 
		"CTY_49_FLG" CHAR(1)  NOT NULL, 
		"CTY_50_FLG" CHAR(1)  NOT NULL, 
		"CTY_51_FLG" CHAR(1)  NOT NULL, 
		"CTY_52_FLG" CHAR(1)  NOT NULL, 
		"CTY_53_FLG" CHAR(1)  NOT NULL, 
		"CTY_54_FLG" CHAR(1)  NOT NULL, 
		"CTY_55_FLG" CHAR(1)  NOT NULL, 
		"CTY_56_FLG" CHAR(1)  NOT NULL, 
		"CTY_57_FLG" CHAR(1)  NOT NULL, 
		"CTY_58_FLG" CHAR(1)  NOT NULL, 
		"CTY_59_FLG" CHAR(1)  NOT NULL, 
		"CTY_60_FLG" CHAR(1)  NOT NULL, 
		"CTY_61_FLG" CHAR(1)  NOT NULL, 
		"CTY_62_FLG" CHAR(1)  NOT NULL, 
		"CTY_63_FLG" CHAR(1)  NOT NULL, 
		"DELETE_DT" DATE WITH DEFAULT NULL
	)CCSID ASCII;
	
CREATE TABLE "CWSINT"."DRMSDOCT" (
		"CREATN_TS" TIMESTAMP NOT NULL, 
		"IDENTIFIER" CHAR(10)  NOT NULL, 
		"DOCHNDL_NM" CHAR(30)  NOT NULL, 
		"LST_UPD_ID" CHAR(3)  NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKDOCTMPLT" CHAR(10)  NOT NULL, 
		"FKSTFPERST" CHAR(3)  WITH DEFAULT NULL, 
		"FKFPSTFPRT" CHAR(3)  WITH DEFAULT NULL
	)CCSID ASCII;
	
CREATE TABLE "CWSINT"."DOCTMPLT" (
		"THIRD_ID" CHAR(10)  NOT NULL, 
		"APL_CTXC" SMALLINT NOT NULL, 
		"DDOS_FNM" CHAR(8)  NOT NULL, 
		"TPLHNDL_NM" CHAR(30)  NOT NULL, 
		"LANG_TPC" SMALLINT NOT NULL, 
		"TITLE_NM" CHAR(40)  NOT NULL, 
		"GVR_ENTC" SMALLINT NOT NULL WITH DEFAULT, 
		"INACT_IND" CHAR(1)  NOT NULL WITH DEFAULT, 
		"TRNS_TYPE" CHAR(1)  NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL WITH DEFAULT '2000-01-01-00.00.00.000000'
	)CCSID ASCII;

CREATE TABLE "CWSINT"."DL_SVC_T" (
		"IDENTIFIER" CHAR(10)  NOT NULL, 
		"CMM_MTHC" SMALLINT NOT NULL WITH DEFAULT, 
		"CNT_LOC" SMALLINT NOT NULL WITH DEFAULT, 
		"CNT_VST_CD" CHAR(1)  NOT NULL, 
		"DETAIL_TXT" CHAR(10)  WITH DEFAULT NULL, 
		"END_DT" DATE WITH DEFAULT NULL, 
		"END_TM" TIME WITH DEFAULT NULL, 
		"DOC_FL_CD" CHAR(1)  NOT NULL, 
		"PROVD_BYID" CHAR(10)  WITH DEFAULT NULL, 
		"PROVD_BYCD" CHAR(1)  WITH DEFAULT NULL, 
		"SVC_CNTC" SMALLINT NOT NULL WITH DEFAULT, 
		"START_DT" DATE NOT NULL, 
		"START_TM" TIME WITH DEFAULT NULL, 
		"STATUS_CD" CHAR(1)  NOT NULL, 
		"SUPRVSN_CD" CHAR(1)  NOT NULL WITH DEFAULT, 
		"LST_UPD_ID" CHAR(3)  NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKDL_SVC_T" CHAR(10)  WITH DEFAULT NULL, 
		"OTHPTC_DSC" CHAR(100)  NOT NULL WITH DEFAULT, 
		"CNTY_SPFCD" CHAR(2)  NOT NULL, 
		"DTL2_TXT" CHAR(10)  WITH DEFAULT NULL, 
		"WRAPSVCIND" CHAR(1)  NOT NULL WITH DEFAULT 'N'
	)CCSID ASCII;
	
CREATE TABLE "CWSINT"."IDV_SVCT" (
		"DEL_IDV_CD" CHAR(1)  NOT NULL, 
		"DEL_IDV_ID" CHAR(10)  NOT NULL, 
		"LST_UPD_ID" CHAR(3)  NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKDL_SVC_T" CHAR(10)  NOT NULL, 
		"CNTY_SPFCD" CHAR(2)  NOT NULL, 
		"SVC_CNTC" SMALLINT NOT NULL WITH DEFAULT, 
		"START_DT" DATE NOT NULL WITH DEFAULT, 
		"END_DT" DATE WITH DEFAULT NULL
	)CCSID ASCII;
	
CREATE TABLE "CWSINT"."RFDLSVCT" (
		"LST_UPD_ID" CHAR(3)  NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"FKREFR_CLT" CHAR(10)  NOT NULL, 
		"FKDL_SVC_T" CHAR(10)  NOT NULL, 
		"FKREFR_CL0" CHAR(10)  NOT NULL, 
		"CNTY_SPFCD" CHAR(2)  NOT NULL
	)CCSID ASCII;
	
CREATE INDEX "CWSINT"."ADDRS1IX"
	ON "CWSINT"."ADDRS_T"
	("PRM_TEL_NO"		ASC)
;

CREATE INDEX "CWSINT"."ADDRS2IX"
	ON "CWSINT"."ADDRS_T"
	("STREET_NM"		ASC, 
	  "ZIP_NO"		ASC, 
	  "CITY_NM"		ASC, 
	  "GVR_ENTC"		ASC)
;

CREATE INDEX "CWSINT"."ADDRS3IX"
	ON "CWSINT"."ADDRS_T"
	("STREET_NM"		ASC)
;

CREATE INDEX "CWSINT"."ADDRS4X"
	ON "CWSINT"."ADDRS_T"
	("STREET_NO"		ASC)
;

CREATE INDEX "CWSINT"."ADDRS5X"
	ON "CWSINT"."ADDRS_T"
	("CITY_NM"		ASC)
;

CREATE INDEX "CWSINT"."ADDRS7X"
	ON "CWSINT"."ADDRS_T"
	("ZIP_NO"		ASC, 
	  "ZIP_SFX_NO"		ASC)
;

CREATE INDEX "CWSINT"."REFERL1X"
	ON "CWSINT"."REFERL_T"
	("FKSTFPERST"		ASC, 
	  "RSP_DTR_DT"		ASC, 
	  "RFRD_RSC"		ASC, 
	  "IDENTIFIER"		ASC)
;

CREATE INDEX "CWSINT"."REFERL2X"
	ON "CWSINT"."REFERL_T"
	("FKSTFPERST"		ASC, 
	  "IDENTIFIER"		ASC, 
	  "REF_RCV_DT"		ASC, 
	  "RFR_RSPC"		ASC)
;

CREATE INDEX "CWSINT"."REFERL3X"
	ON "CWSINT"."REFERL_T"
	("REFCLSR_DT"		ASC, 
	  "GVR_ENTC"		ASC)
;

CREATE INDEX "CWSINT"."REFERL4X"
	ON "CWSINT"."REFERL_T"
	("REFCLSR_DT"		ASC, 
	  "RSP_DTR_DT"		ASC)
;

CREATE INDEX "CWSINT"."REFERL77"
	ON "CWSINT"."REFERL_T"
	("CHILOC_TXT"		ASC)
;

CREATE INDEX "CWSINT"."REFERL88"
	ON "CWSINT"."REFERL_T"
	("FKADDRS_T"		ASC)
;

CREATE INDEX "CWSINT"."REFERL99"
	ON "CWSINT"."REFERL_T"
	("FKREFERL_T"		ASC)
;

CREATE INDEX "CWSINT"."REFERLAA"
	ON "CWSINT"."REFERL_T"
	("FKSTFPERS0"		ASC)
;

CREATE INDEX "CWSINT"."REFERLBB"
	ON "CWSINT"."REFERL_T"
	("RSP_RTNTXT"		ASC)
;

CREATE INDEX "CWSINT"."REFERLCC"
	ON "CWSINT"."REFERL_T"
	("SCN_NT_TXT"		ASC)
;

CREATE INDEX "CWSINT"."REFERLDD"
	ON "CWSINT"."REFERL_T"
	("ALGDSC_DOC"		ASC)
;

CREATE INDEX "CWSINT"."REFERLEE"
	ON "CWSINT"."REFERL_T"
	("ER_REF_DOC"		ASC)
;

CREATE INDEX "CWSINT"."REFERLFF"
	ON "CWSINT"."REFERL_T"
	("INVSTG_DOC"		ASC)
;

CREATE INDEX "CWSINT"."REFERLGG"
	ON "CWSINT"."REFERL_T"
	("APRVL_NO"		ASC)
;

CREATE INDEX "CWSINT"."REFERLHH"
	ON "CWSINT"."REFERL_T"
	("RSP_DTR_DT"		ASC, 
	  "IDENTIFIER"		ASC)
;

CREATE INDEX "CWSINT"."REFRELDD"
	ON "CWSINT"."REFERL_T"
	("ALGDSC_DOC"		ASC)
;

CREATE INDEX "CWSINT"."ALGTN1IX"
	ON "CWSINT"."ALLGTN_T"
	("FKREFERL_T"		ASC, 
	  "ALG_TPC"		ASC)
;

CREATE INDEX "CWSINT"."ALGTN2IX"
	ON "CWSINT"."ALLGTN_T"
	("FKCLIENT_T"		ASC, 
	  "FKCLIENT_0"		ASC)
;

CREATE INDEX "CWSINT"."ALLGTN22"
	ON "CWSINT"."ALLGTN_T"
	("FKCLIENT_T"		ASC)
;

CREATE INDEX "CWSINT"."ALLGTN33"
	ON "CWSINT"."ALLGTN_T"
	("FKCLIENT_0"		ASC)
;

CREATE INDEX "CWSINT"."ALLGTN44"
	ON "CWSINT"."ALLGTN_T"
	("FKCLIENT_T"		ASC, 
	  "FKREFERL_T"		ASC, 
	  "ALG_DSPC"		ASC)
;

CREATE INDEX "CWSINT"."ASGNM1IX"
	ON "CWSINT"."ASGNM_T"
	("ESTBLSH_ID"		ASC, 
	  "ESTBLSH_CD"		ASC, 
	  "ASGNMNT_CD"		ASC, 
	  "FKCASE_LDT"		ASC)
;

CREATE INDEX "CWSINT"."ASGNM2IX"
	ON "CWSINT"."ASGNM_T"
	("FKCASE_LDT"		ASC, 
	  "END_DT"		ASC, 
	  "ASGNMNT_CD"		ASC)
	CLUSTER
;

CREATE INDEX "CWSINT"."ASGNM3IX"
	ON "CWSINT"."ASGNM_T"
	("START_DT"		ASC, 
	  "END_DT"		ASC)
;

CREATE INDEX "CWSINT"."ASGNM4IX"
	ON "CWSINT"."ASGNM_T"
	("FKOST_PTYT"		ASC)
;

CREATE INDEX "CWSINT"."ASGNM5IX"
	ON "CWSINT"."ASGNM_T"
	("FKCASE_LDT"		ASC, 
	  "START_DT"		ASC)
;

CREATE INDEX "CWSINT"."ASGNM6IX"
	ON "CWSINT"."ASGNM_T"
	("END_DT"		ASC)
;

CREATE INDEX "CWSINT"."ASGNMT4X"
	ON "CWSINT"."ASGNM_T"
	("FKOST_PTYT"		ASC)
;

CREATE INDEX "CWSINT"."CASE22"
	ON "CWSINT"."CASE_T"
	("FKCHLD_CLT"		ASC, 
	  "START_DT"		ASC)
;

CREATE INDEX "CWSINT"."CASE3X"
	ON "CWSINT"."CASE_T"
	("START_DT"		ASC, 
	  "GVR_ENTC"		ASC)
;

CREATE INDEX "CWSINT"."CASE4X"
	ON "CWSINT"."CASE_T"
	("IDENTIFIER"		ASC, 
	  "START_DT"		DESC)
;

CREATE INDEX "CWSINT"."CASE5X"
	ON "CWSINT"."CASE_T"
	("APRVL_NO"		ASC)
;

CREATE INDEX "CWSINT"."CASE6X"
	ON "CWSINT"."CASE_T"
	("END_DT"		ASC)
;

CREATE INDEX "CWSINT"."CASE7X"
	ON "CWSINT"."CASE_T"
	("FKREFERL_T"		ASC)
;

CREATE INDEX "CWSINT"."CASE8X"
	ON "CWSINT"."CASE_T"
	("ALERT_TXT"		ASC)
;

CREATE INDEX "CWSINT"."CASET444"
	ON "CWSINT"."CASE_T"
	("CL_STM_TXT"		ASC)
;

CREATE INDEX "CWSINT"."CASET555"
	ON "CWSINT"."CASE_T"
	("FKSTFPERST"		ASC)
;

CREATE INDEX "CWSINT"."CASET666"
	ON "CWSINT"."CASE_T"
	("NOTES_DOC"		ASC)
;

CREATE INDEX "CWSINT"."CRSSR22"
	ON "CWSINT"."CRSS_RPT"
	("FKREFERL_T"		ASC, 
	  "INFORM_DT"		ASC, 
	  "XRPT_MTC"		ASC)
;

CREATE INDEX "CWSINT"."CRSSRP44"
	ON "CWSINT"."CRSS_RPT"
	("FKLAW_ENFT"		ASC)
;

CREATE INDEX "CWSINT"."CRSSRP55"
	ON "CWSINT"."CRSS_RPT"
	("FKSTFPERST"		ASC)
;

CREATE UNIQUE INDEX "CWSINT"."CRSSR33"
	ON "CWSINT"."CRSS_RPT"
	("THIRD_ID"		ASC)
;

CREATE INDEX "CWSINT"."GRVREQ11"
	ON "CWSINT"."GRV_REQT"
	("FKCLIENT_T"		ASC)
;

CREATE INDEX "CWSINT"."OTHDOC1X"
	ON "CWSINT"."OTH_DOCT"
	("FKREFERL_T"		ASC)
;
	
CREATE INDEX "CWSINT"."REFRCL1X"
	ON "CWSINT"."REFR_CLT"
	("FKREFERL_T"		ASC)
;

CREATE INDEX "CWSINT"."REFRCL2X"
	ON "CWSINT"."REFR_CLT"
	("APRVL_NO"		ASC)
;

CREATE INDEX "CWSINT"."REFRCL3X"
	ON "CWSINT"."REFR_CLT"
	("RCL_DISPDT"		ASC)
;
	
CREATE INDEX "CWSINT"."REFRHIS1"
	ON "CWSINT"."REFRHIST"
	("FKSTFPERST"		ASC)
;

CREATE INDEX "CWSINT"."REPTR111"
	ON "CWSINT"."REPTR_T"
	("FKLAW_ENFT"		ASC)
;

CREATE INDEX "CWSINT"."REPTR222"
	ON "CWSINT"."REPTR_T"
	("FDBACK_DOC"		ASC)
;

CREATE INDEX "CWSINT"."SPRJRF22"
	ON "CWSINT"."SPRJ_RFT"
	("FKREFERL_T"		ASC)
;

CREATE INDEX "CWSINT"."SPRJRF33"
	ON "CWSINT"."SPRJ_RFT"
	("FKSPC_PRJT"		ASC)
;

CREATE INDEX "CWSINT"."STFPERS2"
	ON "CWSINT"."STFPERST"
	("FKCWS_OFFT"		ASC)
;

CREATE INDEX "CWSINT"."STFPERS3"
	ON "CWSINT"."STFPERST"
	("LAST_NM"		ASC)
;

CREATE INDEX "CWSINT"."STFPERS4"
	ON "CWSINT"."STFPERST"
	("FKCWSADDRT"		ASC)
;

CREATE INDEX "CWSINT"."SPVAPV1X"
	ON "CWSINT"."SPV_APVT"
	("CUR_APVIND"		ASC, 
	  "APV_STC"		ASC)
;

CREATE INDEX "CWSINT"."SPVAPV2X"
	ON "CWSINT"."SPV_APVT"
	("APRVL_NO"		ASC)
;

CREATE INDEX "CWSINT"."SPVAPV3X"
	ON "CWSINT"."SPV_APVT"
	("ESTB_FORID"		ASC, 
	  "ESTB_FORCD"		ASC, 
	  "CUR_APVIND"		ASC, 
	  "APV_STC"		ASC)
;

CREATE INDEX "CWSINT"."SPVAPV4X"
	ON "CWSINT"."SPV_APVT"
	("FKSTFPERST"		ASC, 
	  "FKSTFPERS0"		ASC)
;

CREATE INDEX "CWSINT"."SPVAPV55"
	ON "CWSINT"."SPV_APVT"
	("FKSTFPERS0"		ASC)
;

	
GRANT ALTER ON TABLE "CWSINT"."ALLGTN_T" TO "CWSINT" WITH GRANT OPTION;
GRANT DELETE ON TABLE "CWSINT"."ALLGTN_T" TO "CWSINT" WITH GRANT OPTION;
GRANT INDEX ON TABLE "CWSINT"."ALLGTN_T" TO "CWSINT" WITH GRANT OPTION;
GRANT INSERT ON TABLE "CWSINT"."ALLGTN_T" TO "CWSINT" WITH GRANT OPTION;
GRANT REFERENCES ON TABLE "CWSINT"."ALLGTN_T" TO "CWSINT" WITH GRANT OPTION;
GRANT SELECT ON TABLE "CWSINT"."ALLGTN_T" TO "CWSINT" WITH GRANT OPTION;
GRANT UPDATE ON TABLE "CWSINT"."ALLGTN_T" TO "CWSINT" WITH GRANT OPTION;

GRANT ALTER ON TABLE "CWSINT"."ASGNM_T" TO "CWSINT" WITH GRANT OPTION;
GRANT DELETE ON TABLE "CWSINT"."ASGNM_T" TO "CWSINT" WITH GRANT OPTION;
GRANT INDEX ON TABLE "CWSINT"."ASGNM_T" TO "CWSINT" WITH GRANT OPTION;
GRANT INSERT ON TABLE "CWSINT"."ASGNM_T" TO "CWSINT" WITH GRANT OPTION;
GRANT REFERENCES ON TABLE "CWSINT"."ASGNM_T" TO "CWSINT" WITH GRANT OPTION;
GRANT SELECT ON TABLE "CWSINT"."ASGNM_T" TO "CWSINT" WITH GRANT OPTION;
GRANT UPDATE ON TABLE "CWSINT"."ASGNM_T" TO "CWSINT" WITH GRANT OPTION;

GRANT ALTER ON TABLE "CWSINT"."CASE_T" TO "CWSINT" WITH GRANT OPTION;
GRANT DELETE ON TABLE "CWSINT"."CASE_T" TO "CWSINT" WITH GRANT OPTION;
GRANT INDEX ON TABLE "CWSINT"."CASE_T" TO "CWSINT" WITH GRANT OPTION;
GRANT INSERT ON TABLE "CWSINT"."CASE_T" TO "CWSINT" WITH GRANT OPTION;
GRANT REFERENCES ON TABLE "CWSINT"."CASE_T" TO "CWSINT" WITH GRANT OPTION;
GRANT SELECT ON TABLE "CWSINT"."CASE_T" TO "CWSINT" WITH GRANT OPTION;
GRANT UPDATE ON TABLE "CWSINT"."CASE_T" TO "CWSINT" WITH GRANT OPTION;

GRANT ALTER ON TABLE "CWSINT"."CRSS_RPT" TO "CWSINT" WITH GRANT OPTION;
GRANT DELETE ON TABLE "CWSINT"."CRSS_RPT" TO "CWSINT" WITH GRANT OPTION;
GRANT INDEX ON TABLE "CWSINT"."CRSS_RPT" TO "CWSINT" WITH GRANT OPTION;
GRANT INSERT ON TABLE "CWSINT"."CRSS_RPT" TO "CWSINT" WITH GRANT OPTION;
GRANT REFERENCES ON TABLE "CWSINT"."CRSS_RPT" TO "CWSINT" WITH GRANT OPTION;
GRANT SELECT ON TABLE "CWSINT"."CRSS_RPT" TO "CWSINT" WITH GRANT OPTION;
GRANT UPDATE ON TABLE "CWSINT"."CRSS_RPT" TO "CWSINT" WITH GRANT OPTION;

GRANT ALTER ON TABLE "CWSINT"."GRV_REQT" TO "CWSINT" WITH GRANT OPTION;
GRANT DELETE ON TABLE "CWSINT"."GRV_REQT" TO "CWSINT" WITH GRANT OPTION;
GRANT INDEX ON TABLE "CWSINT"."GRV_REQT" TO "CWSINT" WITH GRANT OPTION;
GRANT INSERT ON TABLE "CWSINT"."GRV_REQT" TO "CWSINT" WITH GRANT OPTION;
GRANT REFERENCES ON TABLE "CWSINT"."GRV_REQT" TO "CWSINT" WITH GRANT OPTION;
GRANT SELECT ON TABLE "CWSINT"."GRV_REQT" TO "CWSINT" WITH GRANT OPTION;
GRANT UPDATE ON TABLE "CWSINT"."GRV_REQT" TO "CWSINT" WITH GRANT OPTION;

GRANT ALTER ON TABLE "CWSINT"."OTH_DOCT" TO "CWSINT" WITH GRANT OPTION;
GRANT DELETE ON TABLE "CWSINT"."OTH_DOCT" TO "CWSINT" WITH GRANT OPTION;
GRANT INDEX ON TABLE "CWSINT"."OTH_DOCT" TO "CWSINT" WITH GRANT OPTION;
GRANT INSERT ON TABLE "CWSINT"."OTH_DOCT" TO "CWSINT" WITH GRANT OPTION;
GRANT REFERENCES ON TABLE "CWSINT"."OTH_DOCT" TO "CWSINT" WITH GRANT OPTION;
GRANT SELECT ON TABLE "CWSINT"."OTH_DOCT" TO "CWSINT" WITH GRANT OPTION;
GRANT UPDATE ON TABLE "CWSINT"."OTH_DOCT" TO "CWSINT" WITH GRANT OPTION;

GRANT ALTER ON TABLE "CWSINT"."REFR_CLT" TO "CWSINT" WITH GRANT OPTION;
GRANT DELETE ON TABLE "CWSINT"."REFR_CLT" TO "CWSINT" WITH GRANT OPTION;
GRANT INDEX ON TABLE "CWSINT"."REFR_CLT" TO "CWSINT" WITH GRANT OPTION;
GRANT INSERT ON TABLE "CWSINT"."REFR_CLT" TO "CWSINT" WITH GRANT OPTION;
GRANT REFERENCES ON TABLE "CWSINT"."REFR_CLT" TO "CWSINT" WITH GRANT OPTION;
GRANT SELECT ON TABLE "CWSINT"."REFR_CLT" TO "CWSINT" WITH GRANT OPTION;
GRANT UPDATE ON TABLE "CWSINT"."REFR_CLT" TO "CWSINT" WITH GRANT OPTION;

GRANT ALTER ON TABLE "CWSINT"."REFRHIST" TO "CWSINT" WITH GRANT OPTION;
GRANT DELETE ON TABLE "CWSINT"."REFRHIST" TO "CWSINT" WITH GRANT OPTION;
GRANT INDEX ON TABLE "CWSINT"."REFRHIST" TO "CWSINT" WITH GRANT OPTION;
GRANT INSERT ON TABLE "CWSINT"."REFRHIST" TO "CWSINT" WITH GRANT OPTION;
GRANT REFERENCES ON TABLE "CWSINT"."REFRHIST" TO "CWSINT" WITH GRANT OPTION;
GRANT SELECT ON TABLE "CWSINT"."REFRHIST" TO "CWSINT" WITH GRANT OPTION;
GRANT UPDATE ON TABLE "CWSINT"."REFRHIST" TO "CWSINT" WITH GRANT OPTION;

GRANT ALTER ON TABLE "CWSINT"."REPTR_T" TO "CWSINT" WITH GRANT OPTION;
GRANT DELETE ON TABLE "CWSINT"."REPTR_T" TO "CWSINT" WITH GRANT OPTION;
GRANT INDEX ON TABLE "CWSINT"."REPTR_T" TO "CWSINT" WITH GRANT OPTION;
GRANT INSERT ON TABLE "CWSINT"."REPTR_T" TO "CWSINT" WITH GRANT OPTION;
GRANT REFERENCES ON TABLE "CWSINT"."REPTR_T" TO "CWSINT" WITH GRANT OPTION;
GRANT SELECT ON TABLE "CWSINT"."REPTR_T" TO "CWSINT" WITH GRANT OPTION;
GRANT UPDATE ON TABLE "CWSINT"."REPTR_T" TO "CWSINT" WITH GRANT OPTION;

GRANT ALTER ON TABLE "CWSINT"."SPRJ_RFT" TO "CWSINT" WITH GRANT OPTION;
GRANT DELETE ON TABLE "CWSINT"."SPRJ_RFT" TO "CWSINT" WITH GRANT OPTION;
GRANT INDEX ON TABLE "CWSINT"."SPRJ_RFT" TO "CWSINT" WITH GRANT OPTION;
GRANT INSERT ON TABLE "CWSINT"."SPRJ_RFT" TO "CWSINT" WITH GRANT OPTION;
GRANT REFERENCES ON TABLE "CWSINT"."SPRJ_RFT" TO "CWSINT" WITH GRANT OPTION;
GRANT SELECT ON TABLE "CWSINT"."SPRJ_RFT" TO "CWSINT" WITH GRANT OPTION;
GRANT UPDATE ON TABLE "CWSINT"."SPRJ_RFT" TO "CWSINT" WITH GRANT OPTION;

GRANT ALTER ON TABLE "CWSINT"."STFPERST" TO "CWSINT" WITH GRANT OPTION;
GRANT DELETE ON TABLE "CWSINT"."STFPERST" TO "CWSINT" WITH GRANT OPTION;
GRANT INDEX ON TABLE "CWSINT"."STFPERST" TO "CWSINT" WITH GRANT OPTION;
GRANT INSERT ON TABLE "CWSINT"."STFPERST" TO "CWSINT" WITH GRANT OPTION;
GRANT REFERENCES ON TABLE "CWSINT"."STFPERST" TO "CWSINT" WITH GRANT OPTION;
GRANT SELECT ON TABLE "CWSINT"."STFPERST" TO "CWSINT" WITH GRANT OPTION;
GRANT UPDATE ON TABLE "CWSINT"."STFPERST" TO "CWSINT" WITH GRANT OPTION;

GRANT ALTER ON TABLE "CWSINT"."SPV_APVT" TO "CWSINT" WITH GRANT OPTION;
GRANT DELETE ON TABLE "CWSINT"."SPV_APVT" TO "CWSINT" WITH GRANT OPTION;
GRANT INDEX ON TABLE "CWSINT"."SPV_APVT" TO "CWSINT" WITH GRANT OPTION;
GRANT INSERT ON TABLE "CWSINT"."SPV_APVT" TO "CWSINT" WITH GRANT OPTION;
GRANT REFERENCES ON TABLE "CWSINT"."SPV_APVT" TO "CWSINT" WITH GRANT OPTION;
GRANT SELECT ON TABLE "CWSINT"."SPV_APVT" TO "CWSINT" WITH GRANT OPTION;
GRANT UPDATE ON TABLE "CWSINT"."SPV_APVT" TO "CWSINT" WITH GRANT OPTION;
	

GRANT ALTER ON TABLE "CWSINT"."ADDRS_T" TO "CWSINT" WITH GRANT OPTION;
GRANT DELETE ON TABLE "CWSINT"."ADDRS_T" TO "CWSINT" WITH GRANT OPTION;
GRANT INDEX ON TABLE "CWSINT"."ADDRS_T" TO "CWSINT" WITH GRANT OPTION;
GRANT INSERT ON TABLE "CWSINT"."ADDRS_T" TO "CWSINT" WITH GRANT OPTION;
GRANT REFERENCES ON TABLE "CWSINT"."ADDRS_T" TO "CWSINT" WITH GRANT OPTION;
GRANT SELECT ON TABLE "CWSINT"."ADDRS_T" TO "CWSINT" WITH GRANT OPTION;
GRANT UPDATE ON TABLE "CWSINT"."ADDRS_T" TO "CWSINT" WITH GRANT OPTION;

GRANT ALTER ON TABLE "CWSINT"."REFERL_T" TO "CWSINT" WITH GRANT OPTION;
GRANT DELETE ON TABLE "CWSINT"."REFERL_T" TO "CWSINT" WITH GRANT OPTION;
GRANT INDEX ON TABLE "CWSINT"."REFERL_T" TO "CWSINT" WITH GRANT OPTION;
GRANT INSERT ON TABLE "CWSINT"."REFERL_T" TO "CWSINT" WITH GRANT OPTION;
GRANT REFERENCES ON TABLE "CWSINT"."REFERL_T" TO "CWSINT" WITH GRANT OPTION;
GRANT SELECT ON TABLE "CWSINT"."REFERL_T" TO "CWSINT" WITH GRANT OPTION;
GRANT UPDATE ON TABLE "CWSINT"."REFERL_T" TO "CWSINT" WITH GRANT OPTION;	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
