package gov.ca.cwds.rest.resources.cms;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.junit.Assert.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;

import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import org.hamcrest.junit.ExpectedException;
import org.junit.Before;
import org.junit.ClassRule;
import org.junit.Rule;
import org.junit.Test;

import gov.ca.cwds.rest.api.domain.cms.CmsDocument;
import gov.ca.cwds.rest.resources.ServiceBackedResourceDelegate;
import gov.ca.cwds.rest.resources.TypedResourceDelegate;
import io.dropwizard.testing.junit.ResourceTestRule;

/**
 * NOTE : The CWDS API Team has taken the pattern of delegating Resource functions to
 * {@link ServiceBackedResourceDelegate}. As such the tests in here reflect that assumption.
 * 
 * @author CWDS API Team
 */
public class CmsDocumentResourceTest {

  private static final String FOUND_RESOURCE = "/cmsdocument/abc";

  @Rule
  public ExpectedException thrown = ExpectedException.none();

  private final static TypedResourceDelegate<String, CmsDocument> resourceDelegate =
      mock(TypedResourceDelegate.class);

  @ClassRule
  public final static ResourceTestRule inMemoryResource =
      ResourceTestRule.builder().addResource(new CmsDocumentResource(resourceDelegate)).build();

  @Before
  public void setup() throws Exception {}

  /**
   * Get Tests
   * 
   * @throws Exception required for test compilation
   */
  @Test
  public void getDelegatesToResourceDelegate() throws Exception {
    inMemoryResource.client().target(FOUND_RESOURCE).request().accept(MediaType.APPLICATION_JSON)
        .get();
    verify(resourceDelegate).get("abc");
  }

  // @Test
  // public void createValidatesEntity() throws Exception {
  // CmsDocument serialized =
  // MAPPER.readValue(fixture("fixtures/domain/cms/CmsDocument/invalid/invalid.json"),
  // CmsDocument.class);
  //
  // int status =
  // inMemoryResource.client().target(ROOT_RESOURCE).request()
  // .accept(MediaType.APPLICATION_JSON)
  // .post(Entity.entity(serialized, MediaType.APPLICATION_JSON)).getStatus();
  // assertThat(status, is(422));
  // }

  @Test
  public void type() throws Exception {
    // TODO auto-generated by JUnit Helper.
    assertThat(CmsDocumentResource.class, notNullValue());
  }

  @Test
  public void instantiation() throws Exception {
    // TODO auto-generated by JUnit Helper.
    TypedResourceDelegate<String, CmsDocument> resourceDelegate = null;
    CmsDocumentResource target = new CmsDocumentResource(resourceDelegate);
    assertThat(target, notNullValue());
  }

  @Test
  public void get_A$String() throws Exception {
    // TODO auto-generated by JUnit Helper.
    TypedResourceDelegate<String, CmsDocument> resourceDelegate = null;
    CmsDocumentResource target = new CmsDocumentResource(resourceDelegate);
    // given
    String id = null;
    // e.g. : given(mocked.called()).willReturn(1);
    // when
    Response actual = target.get(id);
    // then
    // e.g. : verify(mocked).called();
    Response expected = null;
    assertThat(actual, is(equalTo(expected)));
  }

  @Test
  public void delete_A$String() throws Exception {
    // TODO auto-generated by JUnit Helper.
    TypedResourceDelegate<String, CmsDocument> resourceDelegate = null;
    CmsDocumentResource target = new CmsDocumentResource(resourceDelegate);
    // given
    String id = null;
    // e.g. : given(mocked.called()).willReturn(1);
    // when
    Response actual = target.delete(id);
    // then
    // e.g. : verify(mocked).called();
    Response expected = null;
    assertThat(actual, is(equalTo(expected)));
  }

  @Test
  public void create_A$govcacwdsrestapidomaincmsCmsDocument() throws Exception {
    // TODO auto-generated by JUnit Helper.
    TypedResourceDelegate<String, CmsDocument> resourceDelegate = null;
    CmsDocumentResource target = new CmsDocumentResource(resourceDelegate);
    // given
    gov.ca.cwds.rest.api.domain.cms.CmsDocument doc =
        mock(gov.ca.cwds.rest.api.domain.cms.CmsDocument.class);
    // e.g. : given(mocked.called()).willReturn(1);
    // when
    Response actual = target.create(doc);
    // then
    // e.g. : verify(mocked).called();
    Response expected = null;
    assertThat(actual, is(equalTo(expected)));
  }

  @Test
  public void update_A$String$CmsDocument() throws Exception {
    // TODO auto-generated by JUnit Helper.
    TypedResourceDelegate<String, CmsDocument> resourceDelegate = null;
    CmsDocumentResource target = new CmsDocumentResource(resourceDelegate);
    // given
    String id = null;
    CmsDocument doc = mock(CmsDocument.class);
    // e.g. : given(mocked.called()).willReturn(1);
    // when
    Response actual = target.update(id, doc);
    // then
    // e.g. : verify(mocked).called();
    Response expected = null;
    assertThat(actual, is(equalTo(expected)));
  }

}
