/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_ca_cwds_rest_util_jni_KeyJNI */

#ifndef _Included_gov_ca_cwds_rest_util_jni_KeyJNI
#define _Included_gov_ca_cwds_rest_util_jni_KeyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_ca_cwds_rest_util_jni_KeyJNI
 * Method:    generateKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_ca_cwds_rest_util_jni_KeyJNI_generateKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gov_ca_cwds_rest_util_jni_KeyJNI
 * Method:    decomposeKey
 * Signature: (Ljava/lang/String;Lgov/ca/cwds/rest/util/jni/KeyJNI/KeyDetail;)V
 */
JNIEXPORT void JNICALL Java_gov_ca_cwds_rest_util_jni_KeyJNI_decomposeKey
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
