/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_ca_cwds_rest_util_jni_KeyJNI_KeyDetail */

#ifndef _Included_gov_ca_cwds_rest_util_jni_KeyJNI_KeyDetail
#define _Included_gov_ca_cwds_rest_util_jni_KeyJNI_KeyDetail
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
