/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class KeyJNI */

#ifndef _Included_KeyJNI
#define _Included_KeyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     KeyJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_KeyJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     KeyJNI
 * Method:    generateKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_KeyJNI_generateKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     KeyJNI
 * Method:    decomposeKey
 * Signature: (Ljava/lang/String;LKeyJNI/KeyDetail;)V
 */
JNIEXPORT void JNICALL Java_KeyJNI_decomposeKey
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
