/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class KeyJNI_KeyDetail */

#ifndef _Included_KeyJNI_KeyDetail
#define _Included_KeyJNI_KeyDetail
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
