CREATE TABLE "NEWTABLE" (
		"IDENTIFIER" CHAR(3)  NOT NULL,  
		"LST_UPD_ID" CHAR(3)  NOT NULL, 
		"LST_UPD_TS" TIMESTAMP NOT NULL, 
		"TWITTER_NM" CHAR(20)  NOT NULL
	);
	
	
ALTER TABLE "STFPERST" DROP COLUMN "TWITTER_NM";

ALTER TABLE "STFPERST" ADD COLUMN "ADDED" VARCHAR(32);