/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 21-Feb-2017 4:10:30 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS public.seq_ethnicity
;

DROP SEQUENCE IF EXISTS public.seq_race
;

/* Drop Tables */

DROP TABLE IF EXISTS public.ethnicity CASCADE
;

DROP TABLE IF EXISTS public.person_ethnicity CASCADE
;

DROP TABLE IF EXISTS public.person_race CASCADE
;

DROP TABLE IF EXISTS public.race CASCADE
;

/* Create Tables */

CREATE TABLE public.ethnicity
(
	ethnicity_id integer NOT NULL   DEFAULT NEXTVAL(('seq_ethnicity'::text)::regclass),    -- Unique, sequential primary key of the table.
	ethnicity_type_id varchar(50) NOT NULL,    -- The primary ethnicity category (e.g., "Yes" to hispanic/latino) or value  (e.g., unknown) associated with a person.  
	sub_ethnicity_id varchar(50) NULL,    -- A subdivision of an ethnicity (hispanic/latino).  A secondary or subsidiary race under the principle race.  Currently the UI will pass a string value.  Future: FK to LOV table.
	create_user_id varchar(50) NULL,    -- The ID of the user that created the record.
	create_datetime timestamp NULL,    -- The date and time that the create_user created the record.
	update_user_id varchar(50) NULL,    -- The ID of the user that updated the record.   
	update_datetime timestamp NULL    -- The date and time that the update_user updated the record.
)
;

CREATE TABLE public.person_ethnicity
(
	person_id integer NOT NULL,    -- Part of composite PK.  FK to person table.  
	ethnicity_id integer NOT NULL,    -- Part of composite PK.  FK to ethnicity table.  
	create_user_id varchar(50) NULL,    -- The ID of the user that created the record.
	create_datetime timestamp NULL,    -- The date and time that the create_user created the record.
	update_user_id varchar(50) NULL,    -- The ID of the user that updated the record.
	update_datetime timestamp NULL
)
;

CREATE TABLE public.person_race
(
	person_id integer NOT NULL,    -- Part of composite PK.  FK to person table.  
	race_id integer NOT NULL,    -- Part of composite PK.  FK to race table.  
	create_user_id varchar(50) NULL,    -- The ID of the user that created the record.
	create_datetime timestamp NULL,    -- The date and time that the create_user created the record.
	update_user_id varchar(50) NULL,    -- The ID of the user that updated the record.
	update_datetime timestamp NULL
)
;

CREATE TABLE public.race
(
	race_id integer NOT NULL   DEFAULT NEXTVAL(('seq_race'::text)::regclass),    -- Unique, sequential primary key of the table.
	race_type_id varchar(50) NOT NULL,    -- The primary race category (e.g., "white") or value (e.g., "unknown") associated with a person.  
	subrace_type_id varchar(50) NULL,    -- A subdivision of a race.  A secondary or subsidiary race under the principle race.
	create_user_id varchar(50) NULL,    -- The ID of the user that created the record.   .
	create_datetime timestamp NULL,    -- The date and time that the create_user created the record.
	update_user_id varchar(50) NULL,    -- The ID of the user that updated the record.   
	update_datetime timestamp NULL    -- The date and time that the update_user updated the record.
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE public.ethnicity ADD CONSTRAINT PK_ethnicity
	PRIMARY KEY (ethnicity_id)
;

ALTER TABLE public.person_ethnicity ADD CONSTRAINT PK_person_ethnicity
	PRIMARY KEY (person_id,ethnicity_id)
;

CREATE INDEX IXFK_person_ethnicity_ethnicity ON public.person_ethnicity (ethnicity_id ASC)
;

CREATE INDEX IXFK_person_ethnicity_person ON public.person_ethnicity (person_id ASC)
;

ALTER TABLE public.person_race ADD CONSTRAINT PK_person_race
	PRIMARY KEY (person_id,race_id)
;

CREATE INDEX IXFK_person_race_person ON public.person_race (person_id ASC)
;

CREATE INDEX IXFK_person_race_race ON public.person_race (race_id ASC)
;

ALTER TABLE public.race ADD CONSTRAINT PK_race
	PRIMARY KEY (race_id)
;

/* Create Foreign Key Constraints */

ALTER TABLE public.person_ethnicity ADD CONSTRAINT FK_person_ethnicity_ethnicity
	FOREIGN KEY (ethnicity_id) REFERENCES public.ethnicity (ethnicity_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.person_ethnicity ADD CONSTRAINT FK_person_ethnicity_person
	FOREIGN KEY (person_id) REFERENCES public.person (person_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.person_race ADD CONSTRAINT FK_person_race_person
	FOREIGN KEY (person_id) REFERENCES public.person (person_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.person_race ADD CONSTRAINT FK_person_race_race
	FOREIGN KEY (race_id) REFERENCES public.race (race_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE public.ethnicity
	IS 'Stores the ethnicity value or values associated with a person.  Note that as of 2/17/17, a user may specify a single value only (e.g., yes latino/hispanic, no latino/hispanic, unknown, abandoned or declined to answer) that does not allow any other value to be selected; or Latino/hispanic ethnicity and/or sub-race (e.g., race of Latino/hispanic ethnicity and sub-race of Central American).  Storage in the Person table would not allow future multi-selections, should they come up,  '
;

COMMENT ON COLUMN public.ethnicity.ethnicity_id
	IS 'Unique, sequential primary key of the table.'
;

COMMENT ON COLUMN public.ethnicity.ethnicity_type_id
	IS 'The primary ethnicity category (e.g., "Yes" to hispanic/latino) or value  (e.g., unknown) associated with a person.  '
;

COMMENT ON COLUMN public.ethnicity.sub_ethnicity_id
	IS 'A subdivision of an ethnicity (hispanic/latino).  A secondary or subsidiary race under the principle race.  Currently the UI will pass a string value.  Future: FK to LOV table.'
;

COMMENT ON COLUMN public.ethnicity.create_user_id
	IS 'The ID of the user that created the record.'
;

COMMENT ON COLUMN public.ethnicity.create_datetime
	IS 'The date and time that the create_user created the record.'
;

COMMENT ON COLUMN public.ethnicity.update_user_id
	IS 'The ID of the user that updated the record.   '
;

COMMENT ON COLUMN public.ethnicity.update_datetime
	IS 'The date and time that the update_user updated the record.'
;

CREATE SEQUENCE public.seq_ethnicity INCREMENT 1 START 1
;

COMMENT ON TABLE public.person_ethnicity
	IS 'Intersection table that supports the storage of ethnicity associated with a specific person.'
;

COMMENT ON COLUMN public.person_ethnicity.person_id
	IS 'Part of composite PK.  FK to person table.  '
;

COMMENT ON COLUMN public.person_ethnicity.ethnicity_id
	IS 'Part of composite PK.  FK to ethnicity table.  '
;

COMMENT ON COLUMN public.person_ethnicity.create_user_id
	IS 'The ID of the user that created the record.'
;

COMMENT ON COLUMN public.person_ethnicity.create_datetime
	IS 'The date and time that the create_user created the record.'
;

COMMENT ON COLUMN public.person_ethnicity.update_user_id
	IS 'The ID of the user that updated the record.'
;

COMMENT ON TABLE public.person_race
	IS 'Intersection table that supports the storage of race associated with a specific person.'
;

COMMENT ON COLUMN public.person_race.person_id
	IS 'Part of composite PK.  FK to person table.  '
;

COMMENT ON COLUMN public.person_race.race_id
	IS 'Part of composite PK.  FK to race table.  '
;

COMMENT ON COLUMN public.person_race.create_user_id
	IS 'The ID of the user that created the record.'
;

COMMENT ON COLUMN public.person_race.create_datetime
	IS 'The date and time that the create_user created the record.'
;

COMMENT ON COLUMN public.person_race.update_user_id
	IS 'The ID of the user that updated the record.'
;

COMMENT ON TABLE public.race
	IS 'Stores the race value or values associated with a person.  Note that as of 2/17/17, a user may specify a single value only (e.g., unknown, abandoned or declined to answer) that does not allow any other value to be selected; One-to-many races (e.g., "white") without subtype; or one-to-many races and/or subraces (e.g., race of "white" and subrace of Armenian) '
;

COMMENT ON COLUMN public.race.race_id
	IS 'Unique, sequential primary key of the table.'
;

COMMENT ON COLUMN public.race.race_type_id
	IS 'The primary race category (e.g., "white") or value (e.g., "unknown") associated with a person.  '
;

COMMENT ON COLUMN public.race.subrace_type_id
	IS 'A subdivision of a race.  A secondary or subsidiary race under the principle race.'
;

COMMENT ON COLUMN public.race.create_user_id
	IS 'The ID of the user that created the record.   .'
;

COMMENT ON COLUMN public.race.create_datetime
	IS 'The date and time that the create_user created the record.'
;

COMMENT ON COLUMN public.race.update_user_id
	IS 'The ID of the user that updated the record.   '
;

COMMENT ON COLUMN public.race.update_datetime
	IS 'The date and time that the update_user updated the record.'
;

CREATE SEQUENCE public.seq_race INCREMENT 1 START 1
;